name: 'dbt_data_guardian'
version: '1.0.0'

profile: 'dbt_data_guardian'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_data_guardian:
    +persist_docs:
      relation: true
      columns: true
    sample:
      +materialized: view
    raw:
      +materialized: view
    staging:
      +materialized: view
    dq:
      +materialized: view
      demo:
        +materialized: table
    data_vault__hub:
      +materialized: table
    data_vault__link:
      +materialized: table
    data_vault__sat:
      +materialized: table
    data_vault__marts:
      +materialized: view

seeds:
  dbt_data_guardian:
    mock_data:
      column_types:
        ID: varchar
        NAME: varchar
        AGE: varchar
        EMAIL: varchar
    dq_mock_data:
      column_types:
        ID: integer
        NAME: string
        AGE: string
        EMAIL: string
        SALARY: number
    scd2_mock_data:
      column_types:
        CUSTOMER_ID: integer
        NAME: string
        AGE: string
        EMAIL: string
        SALARY: number
        JOINING_DATE: string
        LAST_UPDATED: timestamp
    airport:
      column_types:
        AIRPORT_DOT_CODE: string
        AIRPORT_NAME: string
        AIRPORT_ALPHA_CODE: string
        AIRPORT_WORLD_AREA_CODE: integer
        AIRPORT_CITY_NAME: string
        STATE_GEO_ID: string
        COUNTRY_GEO_ID: string
