name: Run DBT Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 7 * * 1-5'  
  workflow_dispatch:        # Allow manual triggering

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    env:
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      DBT_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
      DBT_ROLE: ${{ secrets.DBT_ROLE }}
      DBT_DATABASE: ${{ secrets.DBT_DATABASE }}
      DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}
      DBT_WAREHOUSE: ${{ secrets.DBT_WAREHOUSE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          dbt_data_guardian:
            outputs:
              dev:
                type: snowflake
                account: $DBT_ACCOUNT
                user: $DBT_USER
                password: $DBT_PASSWORD
                role: $DBT_ROLE
                database: $DBT_DATABASE
                warehouse: $DBT_WAREHOUSE
                schema: $DBT_SCHEMA
                threads: 4
            target: dev
          EOF

      - name: Run dbt
        run: |
          dbt debug
          dbt test --select path:tests/ || true
